# ---- PICRUSt2 → PRMT pipeline config (final) ----

inputs:
  # PICRUSt2 unstratified table you want to use:
  #   - EC:  results/picrust2/ec_pred_metagenome.tsv
  #   - KO:  results/picrust2/ko_pred_metagenome.tsv
  #   - PWY: results/picrust2/pathways_out/path_abun_unstrat.tsv
  abundance_table: "results/picrust2/ec_pred_metagenome.tsv"
  # First column name in that table:
  #   EC/KO → "function", Pathways → "pathway"
  id_col: "function"
  metadata: "inst/extdata/metadata.tsv"
  prmt_mapping: "inst/extdata/prmt_mapping.tsv"

processing:
  normalize: "relative"     # "relative" | "none"

scoring:
  method: "sum"             # "sum" | "mean"

output:
  dir: "results"            # used by BOTH R scripts
  prefix: "prmt"
  # filename for reaction_mapformula when you run the KEGG builder:
  mapformula_file: "reaction_mapformula.tsv"

# Section for building KEGG-based mapping (only if you run build_prmt_mapping.R)
kegg:
  kgml_dir: "kgml_files"
  scan_reactions: false      # true = slow, walks reactions via REST
  checkpoint: "processed_reactions.RDS"
  # File with KO↔Reaction links (2 columns: KO, Rxn); see note below to fetch:
  kos_to_rxns_file: "inst/extdata/reference/kos_rxns.tsv"
  kolist: []                 # e.g. ["K00001","K00002"] to restrict; empty = all
  all_kegg_prefix: "all_kegg"  # prefix for saved *_KeggReactions.rda

